---
- name: Create Zookeeper Dir
  ansible.builtin.file:
    path: /opt/zookeeper
    state: directory
    mode: '0755'

- name: Get Zookeeper Binaries
  ansible.builtin.unarchive:
    src: '{{ zookeeper_package }}'
    dest: /opt/zookeeper
    remote_src: yes
    owner: root
    group: root
    extra_opts:
      - "--wildcards"
      - "apache-zookeeper-{{ zookeeper_version }}-bin/bin/*.sh"
      - "apache-zookeeper-{{ zookeeper_version }}-bin/lib/*.jar"
      - "apache-zookeeper-{{ zookeeper_version }}-bin/conf/"
      - "--strip-components=1"

- name: Create Zookeeper Data Dir
  ansible.builtin.file:
    path: /data/zookeeper
    state: directory
    mode: '0755'

- name: Set myid
  ansible.builtin.template:
    src: myid.j2
    dest: /data/zookeeper/myid
    owner: root
    group: root
    mode: '0644'

- name: Set Zookeeper Config
  ansible.builtin.template:
    src: zookeeper.cfg.j2
    dest: /opt/zookeeper/conf/zookeeper.cfg
    owner: root
    group: root
    mode: '0644'

- name: Set Zookeeper Systemd Unit File
  ansible.builtin.template:
    src: zookeeper.service.j2
    dest: /etc/systemd/system/zookeeper.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - daemon-reload

- name: Start and Enable Zookeeper
  ansible.builtin.systemd:
    name: zookeeper
    state: started
    enabled: yes

- name: Open Zookeeper firewall ports
  ansible.posix.firewalld:
    port: '{{ item }}'
    permanent: yes
    immediate: yes
    state: enabled
  loop:
    - 2181/tcp
    - 2888/tcp
    - 3888/tcp